version: "3.8"

services:
    jaeger:
        image: jaegertracing/all-in-one:latest
        container_name: jaeger
        ports:
            - "16686:16686" # Jaeger UI
            - "14268:14268" # HTTP collector
            - "14250:14250" # gRPC collector
            - "6831:6831/udp" # UDP collector
            - "6832:6832/udp" # UDP collector
        environment:
            - COLLECTOR_OTLP_ENABLED=true
            - COLLECTOR_ZIPKIN_HOST_PORT=:9411
        networks:
            - things_network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M
                reservations:
                    cpus: "0.1"
                    memory: 256M

networks:
    things_network:
        external: true
