{
 "title": "HTTP Data Schema Thing",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "changes(traefik_service_requests_total{protocol=\"http\", service=\"http-data-schema-thing-test-things@docker\"}[1m])",
     "legendFormat": "Status Code:{{code}}"
    }
   ]
  },
  {
   "title": "property \"bool\"",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{affordance=\"property\",affordanceName=\"bool\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "property \"num\"",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{affordance=\"property\",affordanceName=\"num\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "property \"array\"",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{affordance=\"property\",affordanceName=\"array\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "property \"int\"",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{affordance=\"property\",affordanceName=\"int\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "property \"string\"",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{affordance=\"property\",affordanceName=\"string\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "property \"object\"",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{affordance=\"property\",affordanceName=\"object\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "action \"void-void\" Inputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"void-void\",messageType=\"actionInput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "action \"void-void\" Outputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"void-void\",messageType=\"actionOutput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "Action Invocation Count",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({affordance=\"action\", thing=\"http-data-schema-thing\", op=\"invokeaction\", messageType=\"\"}[$__auto])",
     "legendFormat": "{{affordanceName}}"
    }
   ]
  },
  {
   "title": "action \"void-int\" Inputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"void-int\",messageType=\"actionInput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "action \"void-int\" Outputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"void-int\",messageType=\"actionOutput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "action \"int-void\" Inputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"int-void\",messageType=\"actionInput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "action \"int-void\" Outputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"int-void\",messageType=\"actionOutput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "action \"int-int\" Inputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"int-int\",messageType=\"actionInput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "action \"int-int\" Outputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"int-int\",messageType=\"actionOutput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "action \"int-string\" Inputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"int-string\",messageType=\"actionInput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "action \"int-string\" Outputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"int-string\",messageType=\"actionOutput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "action \"void-obj\" Inputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"void-obj\",messageType=\"actionInput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "action \"void-obj\" Outputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"void-obj\",messageType=\"actionOutput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "action \"obj-void\" Inputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 56 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"obj-void\",messageType=\"actionInput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  },
  {
   "title": "action \"obj-void\" Outputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 56 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"obj-void\",messageType=\"actionOutput\",op=\"invokeaction\",thing=\"http-data-schema-thing\"}"
    }
   ]
  }
 ]
}