{
 "title": "HTTP Express Calculator Simple",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "changes(traefik_service_requests_total{protocol=\"http\", service=\"http-express-calculator-simple-test-things@docker\"}[1m])",
     "legendFormat": "Status Code:{{code}}"
    }
   ]
  },
  {
   "title": "property \"result\"",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{affordance=\"property\", affordanceName=\"result\",thing=\"http-express-calculator-simple\", messageType=\"updateProperty\"}"
    }
   ]
  },
  {
   "title": "property \"lastChange\"",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{affordance=\"property\",affordanceName=\"lastChange\",thing=\"http-express-calculator-simple\", messageType=\"updateProperty\"}"
    }
   ]
  },
  {
   "title": "Action Invocation Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({affordance=\"action\", thing=\"http-express-calculator-simple\", op=\"invokeaction\", messageType=\"\"}[$__auto])",
     "legendFormat": "{{affordanceName}}"
    }
   ]
  },
  {
   "title": "event \"update\" Subscription Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{affordance=\"event\",affordanceName=\"update\",messageType=\"subscriptionCount\",thing=\"http-express-calculator-simple\"}",
     "legendFormat": "Subscribe {{affordanceName}}"
    }
   ]
  },
  {
   "title": "propert \"result\" Observe Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{affordance=\"property\",affordanceName=\"result\",thing=\"http-express-calculator-simple\", messageType=\"observeCount\"}",
     "legendFormat": "Observe {{affordanceName}}"
    }
   ]
  },
  {
   "title": "action \"add\" Inputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"add\",messageType=\"actionInput\",op=\"invokeaction\",thing=\"http-express-calculator-simple\"}"
    }
   ]
  },
  {
   "title": "action \"add\" Outputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"add\",messageType=\"actionOutput\",op=\"invokeaction\",thing=\"http-express-calculator-simple\"}"
    }
   ]
  },
  {
   "title": "property \"lastChange\" Observe Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{affordance=\"property\",affordanceName=\"lastChange\",thing=\"http-express-calculator-simple\", messageType=\"observeCount\"}",
     "legendFormat": "Observe {{affordanceName}}"
    }
   ]
  },
  {
   "title": "action \"subtract\" Inputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"subtract\",messageType=\"actionInput\",op=\"invokeaction\",thing=\"http-express-calculator-simple\"}"
    }
   ]
  },
  {
   "title": "action \"subtract\" Outputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"subtract\",messageType=\"actionOutput\",op=\"invokeaction\",thing=\"http-express-calculator-simple\"}"
    }
   ]
  }
 ]
}