{
 "title": "MQTT Calculator Thing",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "property \"result\"",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{affordance=\"property\", affordanceName=\"result\",thing=\"mqtt-calculator\", messageType=\"updateProperty\"}"
    }
   ]
  },
  {
   "title": "property \"lastChange\"",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "forward",
     "expr": "{affordance=\"property\",affordanceName=\"lastChange\",thing=\"mqtt-calculator\", messageType=\"updateProperty\"}"
    }
   ]
  },
  {
   "title": "Action Invocation Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({affordance=\"action\", thing=\"mqtt-calculator\", op=\"invokeaction\", messageType=\"\"}[$__auto])",
     "legendFormat": "{{affordanceName}}"
    }
   ]
  },
  {
   "title": "action \"add\" Inputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"add\",messageType=\"actionInput\",op=\"invokeaction\",thing=\"mqtt-calculator\"}"
    }
   ]
  },
  {
   "title": "action \"add\" Outputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"add\",messageType=\"actionOutput\",op=\"invokeaction\",thing=\"mqtt-calculator\"}"
    }
   ]
  },
  {
   "title": "action \"subtract\" Inputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"subtract\",messageType=\"actionInput\",op=\"invokeaction\",thing=\"mqtt-calculator\"}"
    }
   ]
  },
  {
   "title": "action \"subtract\" Outputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{affordance=\"action\",affordanceName=\"subtract\",messageType=\"actionOutput\",op=\"invokeaction\",thing=\"mqtt-calculator\"}"
    }
   ]
  }
 ]
}