FROM node:18-alpine
WORKDIR /app

COPY ./calculator.tm.json .
COPY ./coap/js .

RUN npm install

ARG PORT_ARG=5683
ENV PORT=${PORT_ARG}
ENV TM_PATH="./calculator.tm.json"

CMD ["node", "coap-simple-calculator.js"]

EXPOSE ${PORT}/udp