FROM node:18-alpine
WORKDIR /app

COPY ./calculator.tm.json .
COPY ./coap/js .

RUN npm install

# To be able to expose the given port we use port argument, if exposing the port is not necessary we can simply remove them in the future.
ARG PORT_ARG=5683
ENV PORT=${PORT_ARG}
ENV TM_PATH="./calculator.tm.json"

CMD ["node", "coap-simple-calculator.js"]

EXPOSE ${PORT}/udp