FROM node:18-alpine
WORKDIR /app

COPY ./calculator.tm.json .
COPY ./http/express .

RUN npm install

ARG PORT_ARG=3001
ENV PORT=${PORT_ARG}
ENV TM_PATH="./calculator.tm.json"

CMD ["node", "http-content-negotiation-calculator.js"]

EXPOSE ${PORT}